config/routes.rb
Rails.application.routes.draw do
  resources :proverbs

  root 'proverbs#index'

end

app/models/proverb.rb
class Proverb
  include Cequel::Record

  key :id, :timeuuid, auto: true
  column :wisdom, :text
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/proverbs_controller.rb
class ProverbsController < ApplicationController
  before_action :set_proverb, only: [:show, :edit, :update, :destroy]

  # GET /proverbs
  # GET /proverbs.json
  def index
    @proverbs = Proverb.all
  end

  # GET /proverbs/1
  # GET /proverbs/1.json
  def show
  end

  # GET /proverbs/new
  def new
    @proverb = Proverb.new
  end

  # GET /proverbs/1/edit
  def edit
  end

  # POST /proverbs
  # POST /proverbs.json
  def create
    @proverb = Proverb.new(proverb_params)

    respond_to do |format|
      if @proverb.save
        format.html { redirect_to @proverb, notice: 'Proverb was successfully created.' }
        format.json { render :show, status: :created, location: @proverb }
      else
        format.html { render :new }
        format.json { render json: @proverb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proverbs/1
  # PATCH/PUT /proverbs/1.json
  def update
    respond_to do |format|
      if @proverb.update(proverb_params)
        format.html { redirect_to @proverb, notice: 'Proverb was successfully updated.' }
        format.json { render :show, status: :ok, location: @proverb }
      else
        format.html { render :edit }
        format.json { render json: @proverb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proverbs/1
  # DELETE /proverbs/1.json
  def destroy
    @proverb.destroy
    respond_to do |format|
      format.html { redirect_to proverbs_url, notice: 'Proverb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proverb
      @proverb = Proverb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proverb_params
      params.require(:proverb).permit(:wisdom)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proverbs_helper.rb
module ProverbsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAppWithCassandra</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/proverbs/_form.html.erb
<%= form_for(@proverb) do |f| %>
  <% if @proverb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proverb.errors.count, "error") %> prohibited this proverb from being saved:</h2>

      <ul>
      <% @proverb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wisdom %><br>
    <%= f.text_field :wisdom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proverbs/edit.html.erb
<h1>Editing proverb</h1>

<%= render 'form' %>

<%= link_to 'Show', @proverb %> |
<%= link_to 'Back', proverbs_path %>

app/views/proverbs/index.html.erb
<h1>Listing proverbs</h1>

<table>
  <thead>
    <tr>
      <th>Wisdom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proverbs.each do |proverb| %>
      <tr>
        <td><%= proverb.wisdom %></td>
        <td><%= link_to 'Show', proverb %></td>
        <td><%= link_to 'Edit', edit_proverb_path(proverb) %></td>
        <td><%= link_to 'Destroy', proverb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proverb', new_proverb_path %>

app/views/proverbs/new.html.erb
<h1>New proverb</h1>

<%= render 'form' %>

<%= link_to 'Back', proverbs_path %>

app/views/proverbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wisdom:</strong>
  <%= @proverb.wisdom %>
</p>

<%= link_to 'Edit', edit_proverb_path(@proverb) %> |
<%= link_to 'Back', proverbs_path %>